project_id = "ccnohdogovmnttrlkmex"

[functions.send-alert-email]
verify_jwt = true

[functions.generate-alert-content]
verify_jwt = false

[functions.parent-chatbot]
verify_jwt = false

[functions.neo-voice-chat]
verify_jwt = false
